const DateTabs = () => {
    return (<div className="date-tabs" > <RdsButton badgeLayout="Text_only"
        badgeState="default"
        badgeStyle="primary"
        colorVariant="primary"
        databstoggle="tooltip"
        displayType="Text"
        label="DAY"
        shape="rectangle"
        size="medium"
        state="active"
        style="filled"
        textCase="uppercase"
        tooltipPlacement="LeftArrow"
        tooltipTitle="This is tooltip"
    /> <RdsButton badgeLayout="Text_only"
        badgeState="default"
        badgeStyle="primary"
        colorVariant="default"
        databstoggle="tooltip"
        displayType="Text"
        label="WEEK"
        shape="rectangle"
        size="medium"
        state="default"
        style="outline"
        textCase="uppercase"
        tooltipPlacement="LeftArrow"
        tooltipTitle="This is tooltip"
        /> <RdsButton badgeLayout="Text_only"
            badgeState="default"
            badgeStyle="primary"
            colorVariant="default"
            databstoggle="tooltip"
            displayType="Text"
            label="MONTH"
            shape="rectangle"
            size="medium"
            state="default"
            style="outline"
            textCase="uppercase"
            tooltipPlacement="LeftArrow"
            tooltipTitle="This is tooltip"
        /> </div>);
}

    ;

export default DateTabs;